<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PreferredClassification;
use App\Models\PreferredSubClassification;

class PreferredSubClassificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {  
       $preferredClassifications =  PreferredClassification::get();
       
        $classificationData =  [
                                    1 => [    
                                            'Accounts Officers/Clerks',
                                            'Accounts Payable',
                                            'Accounts Receivable/Credit Control',
                                            'Analysis & Reporting',
                                            'Assistant Accountants',
                                            'Audit - External',
                                            'Audit - Internal',
                                            'Bookkeeping & Small Practice Accounting',
                                            'Business Services & Corpor\'ate Advisory',
                                            'Company Secretaries',
                                            'Compliance & Risk',
                                            'Cost Accounting',
                                            'Financial Accounting & Reporting',
                                            'Financial Managers & Controllers',
                                            'Forensic Accounting & Investigation',
                                            'Insolvency & Corporate Recovery',
                                            'Inventory & Fixed Assets',
                                            'Management',
                                            'Management Accounting & Budgeting',
                                            'Payroll',
                                            'Strategy & Planning',
                                            'Systems Accounting & IT Audit',
                                            'Taxation',
                                            'Treasury',
                                            'Other',
                                        ],
                                    2 => [  'Administrative Assistants',
                                            'Client & Sales Administration',
                                            'Contracts Administration',
                                            'Data Entry & Word Processing',
                                            'Office Management',
                                            'PA, EA & Secretarial',
                                            'Receptionists',
                                            'Records Management & Document Control',
                                            'Other'
                                        ], 
                                    3 => [  
                                            'Agency Account Management',
                                            'Art Direction',
                                            'Editing & Publishing',
                                            'Event Management',
                                            'Journalism & Writing',
                                            'Management',
                                            'Media Strategy, Planning & Buying',
                                            'Performing Arts',
                                            'Photography',
                                            'Programming & Production',
                                            'Promotions',
                                            'Other'
                                    ], 
                                    4 => [  
                                            'Account & Relationship Management',
                                            'Analysis & Reporting',
                                            'Banking - Business',
                                            'Banking - Corporate & Institutional',
                                            'Banking - Retail/Branch',
                                            'Client Services',
                                            'Compliance & Risk',
                                            'Corporate Finance & Investment Banking',
                                            'Credit',
                                            'Financial Planning',
                                            'Funds Management',
                                            'Management',
                                            'Mortgages',
                                            'Settlements',
                                            'Stockbroking & Trading',
                                            'Treasury',
                                            'Other',
                                        ], 

                                    5 => [  
                                            'Collections',
                                            'Customer Service - Call Centre',
                                            'Customer Service - Customer Facing',
                                            'Management & Support',
                                            'Sales - Inbound',
                                            'Sales - Outbound',
                                            'Supervisors/Team Leaders',
                                            'Other',
                                        ],
                                    6 => [  
                                            'Board Appointments',
                                            'CEO',
                                            'COO & MD',
                                            'General/Business Unit Manager',
                                            'Other',
                                        ],
                                    7 => [  
                                            'Aged & Disability Support',
                                            'Child Welfare, Youth & Family Services',
                                            'Community Development',
                                            'Employment Services',
                                            'Fundraising',
                                            'Housing & Homelessness Services',
                                            'Indigenous & Multicultural Services',
                                            'Management',
                                            'Volunteer Coordination & Support',
                                            'Other',
                                        ],
                                    8 => [  
                                            'Contracts Management',
                                            'Estimating',
                                            'Foreperson/Supervisors',
                                            'Health, Safety & Environment',
                                            'Management',
                                            'Planning & Scheduling',
                                            'Plant & Machinery Operators',
                                            'Project Management',
                                            'Quality Assurance & Control',
                                            'Surveying',
                                            'Other',
                                        ],
                                    9 => [  
                                            'Analysts',
                                            'Corporate Development',
                                            'Environment & Sustainability Consulting',
                                            'Management & Change Consulting',
                                            'Policy',
                                            'Strategy & Planning',
                                            'Other',
                                        ], 
                                    10 => [  
                                            'Architectural Drafting',
                                            'Architecture',
                                            'Fashion & Textile Design',
                                            'Graphic Design',
                                            'Illustration & Animation',
                                            'Industrial Design',
                                            'Interior Design',
                                            'Landscape Architecture',
                                            'Urban Design & Planning',
                                            'Web & Interaction Design',
                                            'Other',
                                        ], 
                                    11 => [  
                                            
                                                'Childcare & Outside School Hours Care',
                                                'Library Services & Information Management',
                                                'Management - Schools',
                                                'Management - Universities',
                                                'Management - Vocational',
                                                'Research & Fellowships',
                                                'Student Services',
                                                'Teaching - Early Childhood',
                                                'Teaching - Primary',
                                                'Teaching - Secondary',
                                                'Teaching - Tertiary',
                                                'Teaching - Vocational',
                                                'Teaching Aides & Special Needs',
                                                'Tutoring',
                                                'Workplace Training & Assessment',
                                                'Other',
                                        ],
                                    12 => [  
                                            'Aerospace Engineering',
                                            'Automotive Engineering',
                                            'Building Services Engineering',
                                            'Chemical Engineering',
                                            'Civil/Structural Engineering',
                                            'Electrical/Electronic Engineering',
                                            'Engineering Drafting',
                                            'Environmental Engineering',
                                            'Field Engineering',
                                            'Industrial Engineering',
                                            'Maintenance',
                                            'Management',
                                            'Materials Handling Engineering',
                                            'Mechanical Engineering',
                                            'Process Engineering',
                                            'Project Engineering',
                                            'Project Management',
                                            'Supervisors',
                                            'Systems Engineering',
                                            'Water & Waste Engineering',
                                            'Other',

                                        ],
                                    13 => [  
                                            'Agronomy & Farm Services',
                                            'Conservation, Parks & Wildlife',
                                            'Farm Labour',
                                            'Farm Management',
                                            'Fishing & Aquaculture',
                                            'Horticulture',
                                            'Veterinary Services & Animal Welfare',
                                            'Winery & Viticulture',
                                            'Other',

                                        ],
                                    14 => [  
                                            'Air Force',
                                            'Army',
                                            'Emergency Services',
                                            'Government - Federal',
                                            'Government - Local',
                                            'Government - State',
                                            'Navy',
                                            'Police & Corrections',
                                            'Policy, Planning & Regulation',
                                            'Other',
                                        ], 
                                    15 => [ 
                                            'Ambulance/Paramedics',
                                            'Chiropractic & Osteopathic',
                                            'Clinical/Medical Research',
                                            'Dental',
                                            'Dieticians',
                                            'Environmental Services',
                                            'General Practitioners',
                                            'Management',
                                            'Medical Administration',
                                            'Medical Imaging',
                                            'Medical Specialists',
                                            'Natural Therapies & Alternative Medicine',
                                            'Nursing - A & E, Critical Care & ICU',
                                            'Nursing - Aged Care',
                                            'Nursing - Community, Maternal & Child Health',
                                            'Nursing - Educators & Facilitators',
                                            'Nursing - General Medical & Surgical',
                                            'Nursing - High Acuity',
                                            'Nursing - Management',
                                            'Nursing - Midwifery, Neo-Natal, SCN & NICU',
                                            'Nursing - Paediatric & PICU',
                                            'Nursing - Psych, Forensic & Correctional Health',
                                            'Nursing - Theatre & Recovery',
                                            'Optical',
                                            'Pathology',
                                            'Pharmaceuticals & Medical Devices',
                                            'Pharmacy',
                                            'Physiotherapy, OT & Rehabilitation',
                                            'Psychology, Counselling & Social Work',
                                            'Residents & Registrars',
                                            'Sales',
                                            'Speech Therapy',
                                            'Other',

                                        ], 
                                    16 => [ 
                                            
                                            'Airlines',
                                            'Bar & Beverage Staff',
                                            'Chefs/Cooks',
                                            'Front Office & Guest Services',
                                            'Gaming',
                                            'Housekeeping',
                                            'Kitchen & Sandwich Hands',
                                            'Management',
                                            'Reservations',
                                            'Tour Guides',
                                            'Travel Agents/Consultants',
                                            'Waiting Staff',
                                            'Other',

                                        ], 
                                    17 => [  
                                                'Consulting & Generalist HR',
                                                'Industrial & Employee Relations',
                                                'Management - Agency',
                                                'Management - Internal',
                                                'Occupational Health & Safety',
                                                'Organisational Development',
                                                'Recruitment - Agency',
                                                'Recruitment - Internal',
                                                'Remuneration & Benefits',
                                                'Training & Development',
                                                'Other',
                                            ],                                   
                                    18 => [  
                                            'Architects',
                                            'Business/Systems Analysts',
                                            'Computer Operators',
                                            'Consultants',
                                            'Database Development & Administration',
                                            'Developers/Programmers',
                                            'Engineering - Hardware',
                                            'Engineering - Network',
                                            'Engineering - Software',
                                            'Help Desk & IT Support',
                                            'Management',
                                            'Networks & Systems Administration',
                                            'Product Management & Development',
                                            'Programme & Project Management',
                                            'Sales - Pre & Post',
                                            'Security',
                                            'Team Leaders',
                                            'Technical Writing',
                                            'Telecommunications',
                                            'Testing & Quality Assurance',
                                            'Web Development & Production',
                                            'Other',
                                        ], 
                                    19 => [                                     
                                            'Actuarial',
                                            'Assessment',
                                            'Brokerage',
                                            'Claims',
                                            'Fund Administration',
                                            'Management',
                                            'Risk Consulting',
                                            'Superannuation',
                                            'Underwriting',
                                            'Workers\' Compensation',
                                            'Other',
                                        ],
                                    20 => [                                     
                                            'Banking & Finance Law',
                                            'Construction Law',
                                            'Corporate & Commercial Law',
                                            'Criminal & Civil Law',
                                            'Environment & Planning Law',
                                            'Family Law',
                                            'Generalists - In-house',
                                            'Generalists - Law Firm',
                                            'Industrial Relations & Employment Law',
                                            'Insurance & Superannuation Law',
                                            'Intellectual Property Law',
                                            'Law Clerks & Paralegals',
                                            'Legal Practice Management',
                                            'Legal Secretaries',
                                            'Litigation & Dispute Resolution',
                                            'Personal Injury Law',
                                            'Property Law',
                                            'Tax Law',
                                            'Other',
                                        ],  
                                    21 => [                                     
                                            'Analysis & Reporting',
                                            'Assembly & Process Work',
                                            'Aviation Services',
                                            'Couriers, Drivers & Postal Services',
                                            'Fleet Management',
                                            'Freight/Cargo Forwarding',
                                            'Import/Export & Customs',
                                            'Machine Operators',
                                            'Management',
                                            'Pattern Makers & Garment Technicians',
                                            'Pickers & Packers',
                                            'Production, Planning & Scheduling',
                                            'Public Transport & Taxi Services',
                                            'Purchasing, Procurement & Inventory',
                                            'Quality Assurance & Control',
                                            'Rail & Maritime Transport',
                                            'Road Transport',
                                            'Team Leaders/Supervisors',
                                            'Warehousing, Storage & Distribution',
                                            'Other',
                                        ], 
                                    22 => [                                     
                                            'Analysis & Reporting',
                                            'Assembly & Process Work',
                                            'Aviation Services',
                                            'Couriers, Drivers & Postal Services',
                                            'Fleet Management',
                                            'Freight/Cargo Forwarding',
                                            'Import/Export & Customs',
                                            'Machine Operators',
                                            'Management',
                                            'Pattern Makers & Garment Technicians',
                                            'Pickers & Packers',
                                            'Production, Planning & Scheduling',
                                            'Public Transport & Taxi Services',
                                            'Purchasing, Procurement & Inventory',
                                            'Quality Assurance & Control',
                                            'Rail & Maritime Transport',
                                            'Road Transport',
                                            'Team Leaders/Supervisors',
                                            'Warehousing, Storage & Distribution',
                                            'Other',
                                        ], 
                                        
                                    23 => [                                     
                                            'Brand Management',
                                            'Digital & Search Marketing',
                                            'Direct Marketing & CRM',
                                            'Event Management',
                                            'Internal Communications',
                                            'Management',
                                            'Market Research & Analysis',
                                            'Marketing Assistants/Coordinators',
                                            'Marketing Communications',
                                            'Product Management & Development',
                                            'Public Relations & Corporate Affairs',
                                            'Trade Marketing',
                                            'Other',
                                        ], 
                                    24 => [                                     
                                            'Administration',
                                            'Analysts',
                                            'Body Corporate & Facilities Management',
                                            'Commercial Sales, Leasing & Property Mgmt',
                                            'Residential Leasing & Property Management',
                                            'Residential Sales',
                                            'Retail & Property Development',
                                            'Valuation',
                                            'Other',
                                        ], 
                                    25 => [                                     
                                            'Buying',
                                            'Management - Area/Multi-site',
                                            'Management - Department/Assistant',
                                            'Management - Store',
                                            'Merchandisers',
                                            'Planning',
                                            'Retail Assistants',
                                            'Other',
                                        
                                        ],  
                                    26 => [                                     
                                            'Account & Relationship Management',
                                            'Analysis & Reporting',
                                            'Management',
                                            'New Business Development',
                                            'Sales Coordinators',
                                            'Sales Representatives/Consultants',
                                            'Other',
                                        ], 
                                    27 => [                                     
                                            'Biological & Biomedical Sciences',
                                            'Biotechnology & Genetics',
                                            'Chemistry & Physics',
                                            'Environmental, Earth & Geosciences',
                                            'Food Technology & Safety',
                                            'Laboratory & Technical Services',
                                            'Materials Sciences',
                                            'Mathematics, Statistics & Information Sciences',
                                            'Modelling & Simulation',
                                            'Quality Assurance & Control',
                                            'Other',
                                        ],

                                    28 => [                                     
                                        'Self Employment'
                                    ],
                                    29 => [                                     
                                            'Coaching & Instruction',
                                            'Fitness & Personal Training',
                                            'Management',
                                            'Other',
                                        ],
                                    30 => [                                      
                                        'Air Conditioning & Refrigeration',
                                        'Automotive Trades',
                                        'Bakers & Pastry Chefs',
                                        'Building Trades',
                                        'Butchers',
                                        'Carpentry & Cabinet Making',
                                        'Cleaning Services',
                                        'Electricians',
                                        'Fitters, Turners & Machinists',
                                        'Floristry',
                                        'Gardening & Landscaping',
                                        'Hair & Beauty Services',
                                        'Labourers',
                                        'Locksmiths',
                                        'Maintenance & Handyperson Services',
                                        'Nannies & Babysitters',
                                        'Painters & Sign Writers',
                                        'Plumbers',
                                        'Printing & Publishing Services',
                                        'Security Services',
                                        'Tailors & Dressmakers',
                                        'Technicians',
                                        'Welders & Boilermakers',
                                        'Other',

                                    ],
                                ];


                 foreach ($preferredClassifications as $classification) {
                    $classificationId = $classification->id;
                
                    if (isset($classificationData[$classificationId])) {
                        $subClassifications = $classificationData[$classificationId];
                
                        foreach ($subClassifications as $subClassification) {
                            PreferredSubClassification::create([
                                'classification_id' => $classificationId,
                                'sub_classification' => $subClassification,
                            ]);
                        }
                    }
                }
       
    }
         
}
